name: Onsen
version: '1.0-SNAPSHOT'
main: net.azisaba.life.onsen.Onsen
author: albardoo02
api-version: '1.15'

commands:
  onsen:
    description: Life鯖の温泉プラグイン
    aliases: [ofuro, ohuro, bath, hotspring]

permissions:
  onsen.*:
    description: Onsenの全権限
    default: op
  onsen.admin:
    description: Onsenプラグインの権限
    default: op